name: musikin_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.5
  flutter_staggered_grid_view: ^0.4.0
  provider: ^6.0.5
  page_transition: ^2.0.9
  shared_preferences: ^2.1.0
  email_validator: ^2.1.17
  sqflite: ^2.2.6
  google_fonts: ^4.0.4
  smooth_page_indicator: ^1.1.0
  cool_alert: ^2.0.1
  test: ^1.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

fonts:
  - family: Poppins
    fonts:
      - asset: fonts/
